# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone no.')),
                ('message', models.CharField(max_length=50, verbose_name='Reminder Message')),
            ],
            options={
                'db_table': 'reminder_table',
                'verbose_name': 'reminder_table',
                'verbose_name_plural': 'reminder_tables',
            },
        ),
    ]
