# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='reminder_received',
            field=models.BooleanField(default=False),
        ),
    ]
